### PR TITLE
Implementing "interactive" feature

### PR DESCRIPTION
**Pull request by liarco**
Hi @nateplusplus,
sorry to bother you again, but while working on my project I found a limitation that was giving me some issues reaching to my goal. I quickly implemented it the way I need it, I hope you may find it useful and maybe include it in this great library! 😉

### The issue
All layers cover the whole area, so if you have an interactive element at any level (let's say a link for example) you won't be able to click it. Here is an example of this "issue": https://github.com/liarco/pushin-nextjs-reproducer

### My solution
I decided to use the [`pointer-events`](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) property so all layers will let the mouse events pass through them by default, then I added a `data-pushin-interactive` attribute that will toggle the same property on on specific layers as soon as their opacity is higher than `0`. This solution won't allow multiple interactive layers grab mouse events at the same time, but I think it should cover many use cases.

### Example usage
```html
<div class="pushin">
  <div class="pushin-scene">
    <div class="pushin-layer">This is the first layer you'll see.</div>
    <div class="pushin-layer" data-pushin-interactive="true">
      This is a second layer, which will be positioned behind the first one <a href="#">but links should work properly!</a>.
    </div>
  </div>
</div>
```

In this example the link in the second layer will be clickable as soon as it becomes visible.

### Final thoughts
Feel free to make changes or suggest improvements to this solution, I enabled the "Allow edits by maintainers" so you will be able to push changes to this PR directly if you wish.

Thank you for your time.

### CODE REVIEW

**Comment by liarco** [comment]
I reverted the compiled files so they won't get in the way while reviewing the PR.

**Comment by nateplusplus** [comment]
This is a great idea! Thank you! I have been looking for a solution for this and I love your pointer-events suggestion.

After looking at what you've done, I was thinking about whether we could make it even simpler, so I want to run a suggestion by you.

I'm thinking that instead of manually specifying interactive layers, we could assume all layers may contain some interactive elements. I think the true crux of this issue is that we do not ever want the layer element itself to accept pointer events - only elements within each layer should receive pointer events.

However, I think you've also highlighted a second issue, which is that when layers are fully transparent, they should no longer accept pointer events.

Here's what I'm thinking (let me know what you think):

1. `.pushin-layer` itself should never recieve pointer events (`pointer-events: none`)
2. We could automatically toggle a data attribute whenever layers are visible (maybe call it `data-pushin-visible`).
3. When layers are visible, any elements within them should receive pointer events. We could achieve this with something like this:
  ```css
  .pushin-layer {
    pointer-events: none;
  }
  .pushin-layer[data-pushin-visible] * {
    pointer-events: auto;
  }
  ```

**Comment by liarco** [comment]
I really like the idea, very clever solution! 😃 (I didn't know that children elements could override the parent's setting for that!)

This also makes it easy to override the default behavior in edge-cases where a floating element might get in the way of some interactive object below it (e.g. a decorative asset with a transparent corner that gets over a button). Since the default CSS selector is specific to the `.pushin-layer` class, so you can simply override the CSS property with a selector pointing straight to the annoying element.

This is the only edge case that I can think of, and it can be handled easily, so I will update the PR with this new implementation ASAP.

**Comment by nateplusplus** [comment]
Ah yes, good point about that edge case! I think you're right though, hopefully it's easy enough to work around.

Alternatively we could limit the css rule specifically to the typical interactive elements like `a` and `button`, and possibly other form elements? That list might become exhaustive though, and I worry we could miss something.

**Comment by nateplusplus** [comment]
Hey @liarco, just checking in on this. Do you have some time to update this PR soon?

**Comment by liarco** [comment]
Hi @nateplusplus thank you for your patience and sorry for the delay but I'm a bit behind schedule with some work so I won't be able to work on this very soon. I think I'll be able to get back on this next week but I can't say for sure. I will update you in the next couple of days.

**Comment by nateplusplus** [comment]
No worries! I definitely understand, we all have those weeks 😅

I hope you don’t mind, but I would like to take a stab at this since I do have some time to devote to this. I’ll share what I come up with for your feedback.

**Comment by nateplusplus** [comment]
I've opened a new PR for my implementation: #153

**Comment by liarco** [comment]
Hi @nateplusplus, no worries! You had `write` access to this PR so you could push any change to it (there is this cool option on GitHub where you can give access to the original maintainers when opening new PRs), but no problem I'm gonna check that out later today! 😉

**Pull request closed without merging**
